# Generated by Django 5.2.3 on 2025-06-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Failed', 'Failed'), ('Sucess', 'Success')], max_length=10)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('login_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'login_logs',
            },
        ),
    ]
