# Generated by Django 5.2.3 on 2025-06-18 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favourites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favourites',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.file'),
        ),
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.file'),
        ),
        migrations.AddField(
            model_name='filerating',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.file'),
        ),
        migrations.AddField(
            model_name='filerating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filetags',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.file'),
        ),
        migrations.AddField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.folder'),
        ),
        migrations.AddField(
            model_name='file',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.folder'),
        ),
        migrations.AddField(
            model_name='forum',
            name='started_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.forum'),
        ),
        migrations.AddField(
            model_name='reply',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filetags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tag'),
        ),
        migrations.AddField(
            model_name='userreport',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.file'),
        ),
        migrations.AddField(
            model_name='userreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favourites',
            unique_together={('user', 'file')},
        ),
        migrations.AlterUniqueTogether(
            name='filerating',
            unique_together={('user', 'file')},
        ),
        migrations.AlterUniqueTogether(
            name='filetags',
            unique_together={('file', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='userreport',
            unique_together={('user', 'file')},
        ),
    ]
